from django.db import models
from django.contrib.auth.models import User

TAGS = (
     ('4th Dimension/4D','4th Dimension/4D'),
     ('ABAP','ABAP'),
     ('ABC','ABC'),
     ('ActionScript','ActionScript'),
     ('Ada','Ada'),
     ('Agilent VEE','Agilent VEE'),
     ('AngularJs','AngularJs'),
     ('Alice','Alice'),
     ('Angelscript','Angelscript'),
     ('Apex','Apex'),
     ('APL','APL'),
     ('AppleScript','AppleScript'),
     ('Arc','Arc'),
     ('Arduino','Arduino'),
     ('ASP','ASP'),
     ('AspectJ','AspectJ'),
     ('Assembly','Assembly'),
     ('ATLAS','ATLAS'),
     ('Augeas','Augeas'),
     ('AutoHotkey','AutoHotkey'),
     ('AutoIt','AutoIt'),
     ('AutoLISP','AutoLISP'),
     ('Automator','Automator'),
     ('Avenue','Avenue'),
     ('Awk','Awk'),
     ('Bash','Bash'),
     ('(Visual) Basic','(Visual) Basic'),
     ('bc','bc'),
     ('BCPL','BCPL'),
     ('BETA','BETA'),
     ('BlitzMax','BlitzMax'),
     ('Boo','Boo'),
     ('Bourne Shell','Bourne Shell'),
     ('Bro','Bro'),
     ('C','C'),
     ('C Shell','C Shell'),
     ('C#','C#'),
     ('C++','C++'),
     ('C++/CLI','C++/CLI'),
     ('C-Omega','C-Omega'),
     ('Caml','Caml'),
     ('Ceylon','Ceylon'),
     ('CFML','CFML'),
     ('cg','cg'),
     ('Ch','Ch'),
     ('CHILL','CHILL'),
     ('CIL','CIL'),
     ('CL (OS/400)','CL (OS/400)'),
     ('Clarion','Clarion'),
     ('Clean','Clean'),
     ('Clipper','Clipper'),
     ('Clojure','Clojure'),
     ('CLU','CLU'),
     ('COBOL','COBOL'),
     ('Cobra','Cobra'),
     ('CoffeeScript','CoffeeScript'),
     ('ColdFusion','ColdFusion'),
     ('COMAL','COMAL'),
     ('Common Lisp','Common Lisp'),
     ('Coq','Coq'),
     ('cT','cT'),
     ('Curl','Curl'),
     ('D','D'),
     ('Dart','Dart'),
     ('DCL','DCL'),
     ('DCPU-16 ASM','DCPU-16 ASM'),
     ('Delphi/Object Pascal','Delphi/Object Pascal'),
     ('DiBOL','DiBOL'),
     ('Dylan','Dylan'),
     ('E','E'),
     ('eC','eC'),
     ('Ecl','Ecl'),
     ('ECMAScript','ECMAScript'),
     ('EGL','EGL'),
     ('Eiffel','Eiffel'),
     ('Elixir','Elixir'),
     ('Emacs Lisp','Emacs Lisp'),
     ('Erlang','Erlang'),
     ('Etoys','Etoys'),
     ('Euphoria','Euphoria'),
     ('EXEC','EXEC'),
     ('F#','F#'),
     ('Factor','Factor'),
     ('Falcon','Falcon'),
     ('Fancy','Fancy'),
     ('Fantom','Fantom'),
     ('Felix','Felix'),
     ('Forth','Forth'),
     ('Fortran','Fortran'),
     ('Fortress','Fortress'),
     ('(Visual) FoxPro','(Visual) FoxPro'),
     ('Gambas','Gambas'),
     ('GNU Octave','GNU Octave'),
     ('Go','Go'),
     ('Google AppsScript','Google AppsScript'),
     ('Gosu','Gosu'),
     ('Groovy','Groovy'),
     ('Haskell','Haskell'),
     ('haXe','haXe'),
     ('Heron','Heron'),
     ('HPL','HPL'),
     ('HyperTalk','HyperTalk'),
     ('Icon','Icon'),
     ('IDL','IDL'),
     ('Inform','Inform'),
     ('Informix-4GL','Informix-4GL'),
     ('INTERCAL','INTERCAL'),
     ('Io','Io'),
     ('Ioke','Ioke'),
     ('J','J'),
     ('J#','J#'),
     ('JADE','JADE'),
     ('Java','Java'),
     ('Java FX Script','Java FX Script'),
     ('JavaScript','JavaScript'),
     ('JScript','JScript'),
     ('JScript.NET','JScript.NET'),
     ('Julia','Julia'),
     ('Korn Shell','Korn Shell'),
     ('Kotlin','Kotlin'),
     ('LabVIEW','LabVIEW'),
     ('Ladder Logic','Ladder Logic'),
     ('Lasso','Lasso'),
     ('Limbo','Limbo'),
     ('Lingo','Lingo'),
     ('Lisp','Lisp'),
     ('Logo','Logo'),
     ('Logtalk','Logtalk'),
     ('LotusScript','LotusScript'),
     ('LPC','LPC'),
     ('Lua','Lua'),
     ('Lustre','Lustre'),
     ('M4','M4'),
     ('MAD','MAD'),
     ('Magic','Magic'),
     ('Magik','Magik'),
     ('Malbolge','Malbolge'),
     ('MANTIS','MANTIS'),
     ('Maple','Maple'),
     ('Mathematica','Mathematica'),
     ('MATLAB','MATLAB'),
     ('Max/MSP','Max/MSP'),
     ('MAXScript','MAXScript'),
     ('MEL','MEL'),
     ('Mercury','Mercury'),
     ('Mirah','Mirah'),
     ('Miva','Miva'),
     ('ML','ML'),
     ('Monkey','Monkey'),
     ('Modula-2','Modula-2'),
     ('Modula-3','Modula-3'),
     ('MOO','MOO'),
     ('Moto','Moto'),
     ('MS-DOS Batch','MS-DOS Batch'),
     ('MUMPS','MUMPS'),
     ('NATURAL','NATURAL'),
     ('Nemerle','Nemerle'),
     ('Nimrod','Nimrod'),
     ('NQC','NQC'),
     ('NSIS','NSIS'),
     ('Nu','Nu'),
     ('NXT-G','NXT-G'),
     ('Oberon','Oberon'),
     ('Object Rexx','Object Rexx'),
     ('Objective-C','Objective-C'),
     ('Objective-J','Objective-J'),
     ('OCaml','OCaml'),
     ('Occam','Occam'),
     ('ooc','ooc'),
     ('Opa','Opa'),
     ('OpenCL','OpenCL'),
     ('OpenEdge ABL','OpenEdge ABL'),
     ('OPL','OPL'),
     ('Oz','Oz'),
     ('Paradox','Paradox'),
     ('Parrot','Parrot'),
     ('Pascal','Pascal'),
     ('Perl','Perl'),
     ('PHP','PHP'),
     ('Pike','Pike'),
     ('PILOT','PILOT'),
     ('PL/I','PL/I'),
     ('PL/SQL','PL/SQL'),
     ('Pliant','Pliant'),
     ('PostScript','PostScript'),
     ('POV-Ray','POV-Ray'),
     ('PowerBasic','PowerBasic'),
     ('PowerScript','PowerScript'),
     ('PowerShell','PowerShell'),
     ('Processing','Processing'),
     ('Prolog','Prolog'),
     ('Puppet','Puppet'),
     ('Pure Data','Pure Data'),
     ('Python','Python'),
     ('Q','Q'),
     ('R','R'),
     ('Racket','Racket'),
     ('REALBasic','REALBasic'),
     ('REBOL','REBOL'),
     ('Revolution','Revolution'),
     ('REXX','REXX'),
     ('RPG (OS/400)','RPG (OS/400)'),
     ('Ruby','Ruby'),
     ('Rust','Rust'),
     ('S','S'),
     ('S-PLUS','S-PLUS'),
     ('SAS','SAS'),
     ('Sather','Sather'),
     ('Scala','Scala'),
     ('Scheme','Scheme'),
     ('Scilab','Scilab'),
     ('Scratch','Scratch'),
     ('sed','sed'),
     ('Seed7','Seed7'),
     ('Self','Self'),
     ('Shell','Shell'),
     ('SIGNAL','SIGNAL'),
     ('Simula','Simula'),
     ('Simulink','Simulink'),
     ('Slate','Slate'),
     ('Smalltalk','Smalltalk'),
     ('Smarty','Smarty'),
     ('SPARK','SPARK'),
     ('SPSS','SPSS'),
     ('SQR','SQR'),
     ('Squeak','Squeak'),
     ('Squirrel','Squirrel'),
     ('Standard ML','Standard ML'),
     ('Suneido','Suneido'),
     ('SuperCollider','SuperCollider'),
     ('TACL','TACL'),
     ('Tcl','Tcl'),
     ('Tex','Tex'),
     ('thinBasic','thinBasic'),
     ('TOM','TOM'),
     ('Transact-SQL','Transact-SQL'),
     ('Turing','Turing'),
     ('TypeScript','TypeScript'),
     ('Vala/Genie','Vala/Genie'),
     ('VBScript','VBScript'),
     ('Verilog','Verilog'),
     ('VHDL','VHDL'),
     ('Vim','Vim'),
     ('Visual Basic .NET','Visual Basic .NET'),
     ('WebDNA','WebDNA'),
     ('Whitespace','Whitespace'),
     ('X10','X10'),
     ('xBase','xBase'),
     ('XBase++','XBase++'),
     ('Xen','Xen'),
     ('XPL','XPL'),
     ('XSLT','XSLT'),
     ('XQuery','XQuery'),
     ('yacc','yacc'),
     ('Yorick','Yorick'),
     ('Z shell','Z shell'),)

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', null = True)
    subject = models.CharField(max_length=100)
    content = models.TextField(blank = True)
    created = models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now = True)
    def __unicode__(self):
     return u'%s | %s' % (self.user, self.subject)

class Comment(models.Model):
    user = models.ForeignKey(User, related_name='user_comments', null = True)
    post = models.ForeignKey(Post, related_name='post_comments', null = True)
    parent = models.ForeignKey('self', related_name='children_comment', blank=True, null=True)
    content = models.TextField(blank = True)
    upvotes = models.IntegerField(default = 0)
    downvotes = models.IntegerField(default = 0)
    created = models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now = True)
    def __unicode__(self):
     return u'%s' % (self.user)

class Tag(models.Model):
    tag = models.CharField(choices = TAGS, max_length=30)
    post = models.ManyToManyField(Post, related_name='tags')  
    def __unicode__(self):
     return u'%s' % self.tag




